-- Seed idempotente: textos SEO extensos para las 5 marcas.
-- Renderizados en /anteojos-de-sol/[brand] y /anteojos-de-receta/[brand].
--
-- intro: 150-300 palabras debajo del H1.
-- outro: 80-150 palabras al pie de página.
--
-- Reglas de redacción aplicadas:
-- - Español argentino (sin "tú", sin "vosotros").
-- - Mención natural de keyword principal y secundarias.
-- - Honesto: no prometemos cosas que no podemos cumplir.
-- - Sin CTAs duros (eso lo maneja la UI).
-- - Sin "compra ahora" — pensado para SEO, no para sales copy.

BEGIN;

UPDATE public.brands SET
  seo_intro = E'Rusty es una marca de raíces australianas con fuerte presencia argentina, asociada al mundo del surf y el skate desde sus inicios. Su línea de anteojos lleva la misma identidad a la óptica: monturas robustas, formas actuales y paletas pensadas para un público joven que busca anteojos para uso diario, deportivo o casual.\n\nEn Óptica Carballo trabajamos el catálogo Rusty con stock real y respaldo oficial. Tenemos modelos clásicos como wayfarer y rectangulares, junto con formas más contemporáneas como cat-eye y aviador metálico. La mayoría incluyen filtro UV400 (bloqueo del 100% de rayos UVA y UVB) y varias variantes vienen con lentes polarizadas, ideales para manejar, ir a la playa o hacer actividades al aire libre donde los reflejos son intensos.\n\nLos armazones de receta Rusty están pensados para uso diario y se adaptan bien a cristales monofocales estándar. Si tu graduación es elevada o necesitás multifocales, lo coordinamos de forma presencial en nuestra óptica de Virasoro, Corrientes — porque hay mediciones (altura pupilar, postura natural de cabeza) que no se pueden tomar a distancia con la precisión necesaria.\n\nTodos los anteojos Rusty que vendemos incluyen estuche original, franela de microfibra y factura electrónica AFIP. Garantía oficial de 1 año contra defectos de fabricación.',
  seo_outro = E'Si estás buscando anteojos Rusty originales en Argentina, en Óptica Carballo encontrás la línea actualizada con stock real, asesoramiento técnico de óptica matriculada y envíos a todo el país por Correo Argentino. Para consultas puntuales sobre un modelo, compatibilidad con receta o disponibilidad de color, escribinos por WhatsApp y te respondemos en horario comercial.'
WHERE slug = 'rusty';

UPDATE public.brands SET
  seo_intro = E'Vulk es una marca argentina con un catálogo amplio que cubre tanto anteojos de sol como armazones para anteojos de receta. Es una de las opciones más elegidas en el segmento medio del mercado argentino por su relación precio/calidad y la diversidad de modelos disponibles.\n\nEn Óptica Carballo trabajamos las líneas vigentes de Vulk con stock confirmado y respaldo de garantía oficial. Encontrás aviadores clásicos, wayfarer, cuadrados, cat-eye y formas redondas, en materiales que van del acetato (más liviano e hipoalergénico, en muchos colores) al metal (acero inoxidable, más delgado y resistente). Varios modelos de sol incorporan lentes polarizadas y todos los cristales tienen filtro UV400, la protección que recomienda la Organización Mundial de la Salud para uso a la intemperie.\n\nLos armazones de receta Vulk son una buena opción para visión simple y casos estándar. Para graduaciones elevadas, multifocales o bifocales, te recibimos en nuestra óptica de Virasoro para tomar las mediciones correspondientes (DNP, altura pupilar, evaluación del armazón sobre tu rostro).\n\nCada compra incluye estuche original Vulk, franela de microfibra para limpieza, factura electrónica AFIP y la garantía oficial de 1 año contra defectos de fabricación. Si detectás una falla en bisagras, soldaduras o despegado de cristal, escribinos por WhatsApp y gestionamos el cambio o reparación.',
  seo_outro = E'En Óptica Carballo encontrás Vulk oficial con envíos a todo Argentina y la posibilidad de armar tus lentes recetadas online si tu prescripción es estándar, o de forma presencial si requiere mediciones avanzadas. María Carlota Carballo, regente técnica matriculada con más de 30 años en el rubro, supervisa cada armado para asegurar que los cristales se gradúen correctamente y el calce sea adecuado.'
WHERE slug = 'vulk';

UPDATE public.brands SET
  seo_intro = E'Reef es una marca de origen californiano con identidad beach lifestyle y distribución oficial en Argentina. Su línea de anteojos extiende la propuesta de la marca al universo óptico: modelos pensados para uso al aire libre, paletas luminosas y materiales resistentes para acompañar actividades cotidianas.\n\nEn Óptica Carballo trabajamos Reef con stock real y respaldo oficial. El catálogo incluye formas clásicas como wayfarer, aviador y rectangulares, con armazones de acetato y metal. Una parte importante de la línea viene con lentes polarizadas — recomendadas si los vas a usar en playa, pesca, conducción o cualquier situación con reflejos intensos sobre agua, asfalto o vidrio. Todos los cristales filtran rayos UVA y UVB al 100% (filtro UV400).\n\nLa estética Reef se diferencia por buscar combinaciones de color que se relacionan con el universo surf y vacacional, con detalles en bisagras y patillas pensados para uso intensivo. Son anteojos que aguantan el ritmo de uso diario al sol sin perder definición ni comodidad.\n\nCada par incluye estuche original Reef, franela de microfibra, factura electrónica AFIP y garantía oficial de 1 año contra defectos de fabricación. La garantía cubre fallas internas (bisagras, soldaduras, delaminación de cristales); no cubre rotura por golpe ni rayaduras de uso.',
  seo_outro = E'Si buscás anteojos Reef en Argentina con envío a todo el país, en Óptica Carballo encontrás stock real y asesoramiento óptico profesional. Para consultas sobre disponibilidad de un color específico, compatibilidad con receta o detalles técnicos de un modelo, escribinos por WhatsApp y te respondemos rápido.'
WHERE slug = 'reef';

UPDATE public.brands SET
  seo_intro = E'Mormaii nació en Brasil ligada al mundo del surf y hoy tiene presencia consolidada en el mercado argentino con distribución oficial. Es una de las marcas más reconocidas en el segmento deportivo y outdoor: monturas que no se mueven con la actividad, materiales resistentes y diseños pensados para uso intensivo al aire libre.\n\nEn Óptica Carballo trabajamos Mormaii con stock confirmado y garantía oficial. El catálogo incluye modelos clásicos y deportivos en materiales como acetato, metal y tritan (un polímero liviano y flexible, muy resistente al impacto). Varios modelos incorporan patillas con goma antideslizante, lo que los hace una buena elección para correr, andar en bicicleta, hacer kayak, surf o cualquier deporte donde el anteojo tiene que mantenerse en su lugar.\n\nLa mayoría de los modelos vienen con lentes polarizadas — la elección recomendada para deportes náuticos y outdoor donde los reflejos del agua o el asfalto generan fatiga visual y reducen el contraste. Todos los cristales filtran el 100% de los rayos UVA y UVB (filtro UV400).\n\nLos armazones Mormaii admiten armado con cristales recetados en la mayoría de los modelos. Si tu graduación es estándar, lo coordinamos de forma remota; para casos más complejos (multifocales, alta graduación), te recibimos en nuestra óptica para tomar las mediciones necesarias.',
  seo_outro = E'En Óptica Carballo encontrás Mormaii original con envíos a todo Argentina. Si tenés dudas sobre qué modelo se adapta mejor a tu actividad (correr, ir al agua, andar en bici, manejar), escribinos por WhatsApp con el uso que le vas a dar y te recomendamos opciones del catálogo actual con stock real.'
WHERE slug = 'mormaii';

UPDATE public.brands SET
  seo_intro = E'Paula Cahen D''Anvers es una marca argentina con décadas de trayectoria en el mundo de la moda. Su línea de anteojos extiende esa identidad al universo óptico con propuestas femeninas, atemporales y pensadas para combinar con la indumentaria de la marca.\n\nEn Óptica Carballo trabajamos el catálogo Paula Cahen D''Anvers con stock real y respaldo oficial. La línea de anteojos de sol privilegia formas que favorecen el rostro femenino (cat-eye, redondas, aviador suavizado) en paletas neutras y cálidas. Los armazones de acetato vienen en tonos clásicos como negro, carey, miel y nude, junto con apuestas más actuales en celestes, rosados y combinaciones bicolor.\n\nLos cristales tienen filtro UV400 y algunos modelos cuentan con tratamiento polarizado para conducir o usar en exteriores con luz intensa. La calidad de fabricación es buena para uso diario: bisagras firmes, soldaduras prolijas y peso liviano. Es una marca pensada más para uso cotidiano y estético que para alto rendimiento deportivo.\n\nLa línea de armazones para receta sigue la misma estética: monturas elegantes que se prestan bien para armar con cristales monofocales y, en muchos casos, con multifocales bien adaptados. Para ese tipo de armado, te recibimos de forma presencial en nuestra óptica de Virasoro.',
  seo_outro = E'En Óptica Carballo encontrás Paula Cahen D''Anvers oficial con envíos a todo Argentina. Si buscás un modelo específico de la colección actual o querés saber qué opciones tenemos en un color o forma puntual, escribinos por WhatsApp y te enviamos fotos del stock disponible.'
WHERE slug = 'paula-cahen-danvers';

COMMIT;
